Testing To Do App
AbdumurodovaZulfizar/to-do-list-app pull request #3
Opened 2021-08-26 15:46 UTC by AbdumurodovaZulfizar

### Test JavaScript code with Jest

Hello and Good luck to all coders👋👋👋

**_What we have done on this milestone:_**

- write tests for the functions that return a value
- 33 tests in 2 files

by Zulfizar Abdumurodova (Full-Stuck Software developer)
Thanks to all reviewers!

2021-08-26 16:30 UTC, afanimartin requested changes
## changes required 🙏🏿 🙏🏿 🙏🏿 
Nice work writing tests for the todo project. All your tests pass. Well done!

### changes 🔕 🔕 🔕 
- check comments for suggestions

### Martin Afani
#### Slack: whiz25

2021-08-26 16:30 UTC, afanimartin commented on src/model/todoModel.js
> +  // console.log(all(0))
Remove this and other comments from the codebase. Comments make our code look ugly.

2021-08-26 16:30 UTC, afanimartin commented on src/tests/todo_model.test.js
> +  expect(TodoModel.get(0, 0)).toEqual({
- You lack test for the `remove`, `edit` and `save` functions. These functions make up the core business logic of your app. Please add tests for those functions.

2021-08-26 16:30 UTC, afanimartin commented on src/tests/todo_model.test.js
> +  localStorage.setItem('projects', JSON.stringify([{
You have a method called `save` in `projectModel` that adds a new project to `localStorage`. You should use that function here instead of repeating yourself with `localStorage.setItem()`

2021-08-26 16:30 UTC, afanimartin commented on src/tests/todo_model.test.js
> +  localStorage.removeItem('projects');
You should define a method in `projectModel` called `removeProject()` or simply `remove()` to call here. This is a core logic to have in your project and therefore there should be a method for doing that.

2021-08-26 16:30 UTC, afanimartin commented on src/tests/project_model.test.js
> +    localStorage.setItem('projects', JSON.stringify([{
Call the `save(project)` method here instead. All functions must be tested.

2021-08-27 03:44 UTC, AbdumurodovaZulfizar commented on src/tests/project_model.test.js
> +    localStorage.setItem('projects', JSON.stringify([{
Methods are not working in before and after statements, so I have added tests for them.

2021-08-27 03:45 UTC, AbdumurodovaZulfizar commented on src/model/todoModel.js
> +  // console.log(all(0))
Done✅

2021-08-27 03:45 UTC, AbdumurodovaZulfizar commented on src/tests/todo_model.test.js
> +  expect(TodoModel.get(0, 0)).toEqual({
Done ✅

2021-08-27 03:46 UTC, AbdumurodovaZulfizar commented on src/tests/todo_model.test.js
> +  localStorage.setItem('projects', JSON.stringify([{
They are not usable in before and after statements, so I added tests for them.

2021-08-27 03:53 UTC, AbdumurodovaZulfizar commented on src/tests/todo_model.test.js
> +  localStorage.removeItem('projects');
I have added and tested this method, however, I have not used it on the building projects.

2021-08-27 04:12 UTC, rukundoeric approved these changes
Hi @AbdumurodovaZulfizar,

Excellent job on this project. Keep it up 🎆

Congratulations! 🎉 on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-08-27 04:24 UTC, merged